version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: profile_aggregator_web
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      BUNDLE_WITHOUT: ""
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:15-alpine
    container_name: profile_aggregator_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile_aggregator_db_development
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: profile_aggregator_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: profile_aggregator_test
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    env_file:
      - .env
    environment:
      RAILS_ENV: test
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_started
    command: bundle exec rspec

volumes:
  postgres_data:
  redis_data:
  bundle_data:
