default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: profile_aggregator_development
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

test:
  <<: *default
  database: profile_aggregator_test
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

production:
  primary: &primary_production
    <<: *default
    database: profile_aggregator_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    port: <%= ENV["DATABASE_PORT"] %>

  cache:
    <<: *primary_production
    database: profile_aggregator_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: profile_aggregator_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: profile_aggregator_production_cable
    migrations_paths: db/cable_migrate